name: Release CI

on:
  push:
    branches: [ "matrix-build" ]

jobs:
  build-and-publish:
    name: Run build ${{ matrix.VERSION }} ${{ matrix.BUILDER }} ${{ matrix.ARCH }}
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      USER: nix
    strategy:
      matrix:
        BUILDER: ['vmware-iso.vmware']
        ARCH: ['x86_64']
        VERSION: ['25.11', '26.05', 'unstable']
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      if: contains(matrix.BUILDER, 'virtualbox')
      run: |
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
        wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg --dearmor
        sudo apt-get update
        sudo apt-get install -y virtualbox-7.2

    - name: Install dependencies
      if: contains(matrix.BUILDER, 'qemu')
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils libvirt-daemon-system

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run build ${{ matrix.VERSION }} ${{ matrix.BUILDER }} ${{ matrix.ARCH }} and push box to vagrant registry
      if: github.repository == 'nix-community/nixbox'
      env:
        USER: nix
        LOGNAME: nix
        HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
        HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      run: sudo HCP_CLIENT_ID=$HCP_CLIENT_ID HCP_CLIENT_SECRET=$HCP_CLIENT_SECRET make VERSION=${{ matrix.VERSION }} BUILDER=${{ matrix.BUILDER }} packer-build

    - name: Run build  ${{ matrix.VERSION }} ${{ matrix.BUILDER }} ${{ matrix.ARCH }} and push box to vagrant registry
      if: github.repository != 'nix-community/nixbox'
      env:
        USER: nix
        LOGNAME: nix
        HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
        HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      run: sudo HCP_CLIENT_ID=$HCP_CLIENT_ID HCP_CLIENT_SECRET=$HCP_CLIENT_SECRET make VERSION=${{ matrix.VERSION }} BUILDER=${{ matrix.BUILDER }} REPO=${{ vars.HCP_REPO }} packer-build
